### ISSUE TITLE
Does not work on ANY 1.12.2 hybrid server.

### ISSUE THREAD

**Issue by Zilacon** [faceofcat/Tesla-Core-Lib#52]
When using TeslaCoreLib on ANY of the hybrid server projects (CatServer, Atom, Kettle, Mohist) the same crash occurs as follows:
Entire crash report: 
[crash-2019-05-10_02.29.56-server.txt](https://github.com/MinecraftModDevelopmentMods/Tesla-Core-Lib/files/3193816/crash-2019-05-10_02.29.56-server.txt)

Could there please be some form of fix for this?

```net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tesla Core Lib (teslacorelib)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/RenderGlobal
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
    at java.lang.Class.getConstructor0(Class.java:3075)
    at java.lang.Class.getConstructor(Class.java:1825)
    at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:128)
    at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:112)
    at net.ndrei.teslacorelib.blocks.multipart.MultiPartBlockEvents.<clinit>(MultiPartBlockEvents.kt:15)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at net.ndrei.teslacorelib.annotations.BaseAnnotationHandler.process(BaseAnnotationHandler.kt:45)
    at net.ndrei.teslacorelib.BaseProxy.construction(proxies.kt:59)
    at net.ndrei.teslacorelib.TeslaCoreLib.construct(TeslaCoreLib.kt:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.RenderGlobal
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 47 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer com.creativemd.littletiles.LittleTilesTransformer@bc09ff9 from coremod LittlePatchingLoader
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 49 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: oh
    at org.objectweb.asm.ClassWriter.getCommonSuperClass(Unknown Source)
    at org.objectweb.asm.ClassWriter.a(Unknown Source)
    at org.objectweb.asm.Frame.a(Unknown Source)
    at org.objectweb.asm.Frame.a(Unknown Source)
    at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
    at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
    at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
    at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
    at com.creativemd.creativecore.transformer.CreativeTransformer.transform(CreativeTransformer.java:46)
    at com.creativemd.creativecore.transformer.CreativeTransformer.transform(CreativeTransformer.java:32)
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
    ... 51 more```

**Comment by theresajayne** [comment]
Looks like its trying to initialise the Clientside on the server during initialisation
@SideOnly(Side.CLIENT)
@InitializeDuringConstruction
object MultiPartBlockEvents {
    init {
        MinecraftForge.EVENT_BUS.register(this)
    }

**Comment by faceofcat** [comment]
well... maybe it's the "hybrid server"'s fault... I have no idea what a "hybrid server" even is... :(

**Comment by theresajayne** [comment]
Its a Forge Server that also Supports Spigot plugins rather than Sponge., I can't work out much more than that not knowing Kotlin

**Comment by faceofcat** [comment]
well... you could use this as a chance to learn kotlin... kotlin is great! :D 

sorry... but I never played with any spigot/sponge/whatever servers... is there a tutorial or something on how to setup one?... and how to easily test a mod with such a server?

not saying I will have to time to look into this anytime soon... :( ... but... such information would help.

**Comment by theresajayne** [comment]
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/2951307-1-12-2-mohist-high-version-of-cauldron-mcpc

Its basically a Forge Server that also supports Bukkit/Spigot Plugins
